apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgresql-client
    marker: practice
  name: postgresql-client
spec:
  selector:
    matchLabels:
      app: postgresql-client
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels:
        app: postgresql-client
        marker: practice
    spec:
      containers:
        - image: >-
            nexus.local:5000/bitnami/postgresql:14.5.0-debian-11-r14
          command:
            - sh
            - '-c'
            - while true; do sleep 30; done
          name: postgresql-client
          env:
            - name: PG_ADDRESS
              value: 'pg-PG_ID.apps.sbc-okd.pcbltools.ru'
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 128Mi